queue_rules:
  - name: default
    conditions:
      - check-success=Test (yarn lint:cspell)
      - check-success=Test (yarn lint:eslint)
      - check-success=Test (yarn lint:tsc)
      - check-success=Test (yarn lint:unimported)
pull_request_rules:
  - name: update out-of-sync PR
    conditions:
      - base=main
      - -conflict
      - -draft
      - label!=blocked
      - label!=do-not-update
      - '#approved-reviews-by>=1'
    actions:
      update:
  - name: approve self-reviewed PR
    conditions:
      # If you must merge a PR without a review, then use this label
      # to have Mergify merge it for you instead of merging it yourself.
      # This way we at least guarantee that all automated checks pass
      # before changes are merged to the main branch.
      - label!=blocked
      - label=self-review
    actions:
      review:
        type: APPROVE
        message: Automatically approving self-reviewed PR
  - name: label PRs ready for review
    conditions:
      - base=main
      - -draft
      - check-success=Test (yarn lint:cspell)
      - check-success=Test (yarn lint:eslint)
      - check-success=Test (yarn lint:tsc)
      - check-success=Test (yarn lint:unimported)
    actions:
      label:
        add:
          # Addition of this label triggers a GitHub webhook
          # that sends a Slack message to #prs channel.
          - ready-for-review
  - name: merge hotfix
    conditions:
      - base=main
      - -draft
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
      - label!=blocked
      - label=hotfix
    actions:
      queue:
        name: default
        method: rebase
        priority: high
  - name: queue approved PR (high priority)
    conditions:
      - base=main
      - -draft
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
      - label=high-priority
      - check-success=Test (yarn lint:cspell)
      - check-success=Test (yarn lint:eslint)
      - check-success=Test (yarn lint:tsc)
      - check-success=Test (yarn lint:unimported)
    actions:
      queue:
        name: default
        method: rebase
        priority: high
  - name: queue approved PR (low priority)
    conditions:
      - base=main
      - -draft
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
      - label!=blocked
      - label=dependencies
      - label!=hotfix
      - queue-position<=2
      - check-success=Test (yarn lint:cspell)
      - check-success=Test (yarn lint:eslint)
      - check-success=Test (yarn lint:tsc)
      - check-success=Test (yarn lint:unimported)
    actions:
      queue:
        name: default
        method: rebase
        priority: low
  - name: queue approved PR (medium priority)
    conditions:
      - base=main
      - -draft
      - '#approved-reviews-by>=1'
      - '#changes-requested-reviews-by=0'
      - label!=blocked
      - label!=dependencies
      - label!=high-priority
      - label!=hotfix
      - check-success=Test (yarn lint:cspell)
      - check-success=Test (yarn lint:eslint)
      - check-success=Test (yarn lint:tsc)
      - check-success=Test (yarn lint:unimported)
    actions:
      queue:
        name: default
        method: rebase
        priority: medium
  - name: merge Renovate pull request
    conditions:
      - author=renovate[bot]
      - label!=blocked
      - label=dependency-update
      - '#approved-reviews-by>=1'
    actions:
      review:
        type: APPROVE
        message: Automatically approving Renovate
      queue:
        name: default
        method: rebase
        priority: low
  - name: close Renovate pull request (conflict)
    conditions:
      - conflict
      - author=renovate[bot]
      - label=dependency-update
    actions:
      close:
        message: |
          This automated pull request has a conflict. Closing - Renovate will create a new PR.
  - name: close stale pull request
    conditions:
      - base=main
      - -closed
      - updated-at<14 days ago
    actions:
      close:
        message: |
          This pull request looks stale. Feel free to reopen it if you think it is a mistake.