concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.ref }}
jobs:
  lint:
    name: Lint
    runs-on:
      - ubuntu-latest
    steps:
      - name: setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm install yarn -g
      - name: Install Dependencies Backend
        run: |
          cd backend
          yarn
      - name: Yarn lint Backend
        run: |
          cd backend
          yarn lint
      - name: Yarn lint Backend Prettier
        run: |
          cd backend
          yarn lint:prettier
      - name: Install Dependencies Frontend
        run: |
          cd frontend
          yarn
      - name: Yarn lint Frontend
        run: |
          cd frontend
          yarn lint
      - name: Yarn lint Frontend Prettier
        run: |
          cd frontend
          yarn lint:prettier
name: Validate
on:
  pull_request:
    branches:
      - main
    types: 
      - opened
      - synchronize
      - reopened
      - ready_for_review